{{- if index .Values "packages" "emissary-ingress" "hosts" }}
  {{- range $host := index .Values "packages" "emissary-ingress" "hosts" }}
    {{- if $host.tls }}
      {{- $isCertManagerEnabled := false }}
      {{- if $host.tls.certManager }}
        {{- $isCertManagerEnabled = $host.tls.certManager.enabled }}
      {{- end }}
      {{- if not $isCertManagerEnabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: {{ $.Values.organization }}.{{ $.Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ $.Release.Name }}-{{ $host.name }}-tls
  namespace: {{ $.Release.Namespace }}
data:
  tls.crt: {{ $host.tls.crt_b64 | quote }}
  tls.key: {{ $host.tls.key_b64 | quote }}
...
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
