{{- if index .Values "packages" "emissary-ingress" "hosts" }}
  {{- range $host := index .Values "packages" "emissary-ingress" "hosts" }}
    {{- if $host.tls }}
      {{- if $host.tls.client }}
        {{- if $host.tls.client.caCert_b64 }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: {{ $.Values.organization }}.{{ $.Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ $.Release.Name }}-{{ $host.name }}-client-cacert
  namespace: {{ $.Release.Namespace }}
data:
  tls.crt: {{ $host.tls.client.caCert_b64 | quote }}
...
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
