{{- if index .Values "packages" "argo-workflows" "auth" "oidc" "enabled" }}
  {{- range $groupCategory, $_ := index .Values "packages" "argo-workflows" "auth" "oidc" "rbac" }}
    {{- range . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: {{ $.Values.organization }}.{{ $.Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ $.Release.Name }}-rbac-{{ . }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ ternary "argo-workflows-admin" "argo-workflows-view" (eq $groupCategory "adminGroups") }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Release.Name }}-rbac-{{ . }}
    namespace: {{ $.Release.Namespace }}
...
    {{- end }}
  {{- end }}
{{- end }}
