{{- if index .Values "packages" "argo-workflows" "auth" "oidc" "enabled" }}
  {{- range $groupCategory, $_ := index .Values "packages" "argo-workflows" "auth" "oidc" "rbac" }}
    {{- range . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: {{ $.Values.organization }}.{{ $.Values.project }}
    app.kubernetes.io/managed-by: kubepak
  annotations:
    workflows.argoproj.io/rbac-rule: "{{ . | printf "'%s' in groups" }}"
    workflows.argoproj.io/rbac-rule-precedence: "{{ ternary "1" "0" (eq $groupCategory "adminGroups") }}"
  name: {{ $.Release.Name }}-rbac-{{ . }}
  namespace: {{ $.Release.Namespace }}
...
    {{- end }}
  {{- end }}
{{- end }}
