{{- if index .Values "packages" "argo-workflows" "auth" "oidc" "enabled" }}
  {{- $argoWorkflowsDex := index .Values "packages" "argo-workflows" "auth" "oidc" "providers" "dex" }}
  {{- if and $argoWorkflowsDex.clientId $argoWorkflowsDex.clientSecret }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.organization }}.{{ .Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: argo-workflows-auth-oidc-dex
  namespace: {{ .Release.Namespace }}
data:
  client-id: {{ index .Values "packages" "argo-workflows" "auth" "oidc" "providers" "dex" "clientId" | b64enc }}
  client-secret: {{ index .Values "packages" "argo-workflows" "auth" "oidc" "providers" "dex" "clientSecret" | b64enc }}
...
  {{- end }}
{{- end }}
