{{- range $index, $privateRepository := index .Values "packages" "argo-cd" "privateRepositories" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: {{ $.Values.organization }}.{{ $.Values.project }}
    app.kubernetes.io/managed-by: kubepak
    argocd.argoproj.io/secret-type: repository
  name: {{ $.Release.Name }}-repo-creds-{{ $index }}
  namespace: {{ $.Release.Namespace }}
data:
  type: {{ default "git" $privateRepository.type | b64enc | quote }}
  {{- if $privateRepository.name }}
  name: {{ $privateRepository.name | b64enc | quote }}
  {{- end }}
  url: {{ $privateRepository.url | b64enc | quote }}
  {{- if $privateRepository.https }}
  username: {{ $privateRepository.https.username | b64enc | quote }}
  password: {{ $privateRepository.https.password | b64enc | quote }}
  {{- else }}
  sshPrivateKey: {{ $privateRepository.ssh.sshPrivateKey_b64 | quote }}
  {{- end }}
...
{{- end }}
