{{- range $acmeIssuer := index .Values "packages" "cert-manager-issuers" "issuers" "acme" }}
  {{- range $solverIndex, $solverDns01 := $acmeIssuer.solvers.dns01 }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: {{ $.Values.organization }}.{{ $.Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ $.Release.Name }}-{{ $acmeIssuer.name }}-{{ $solverIndex }}
  namespace: {{ index $.Values "packages" "cert-manager" "namespace" }}
data:
  {{- if eq $solverDns01.provider "rfc2136" }}
  tsig-secret: {{ $solverDns01.rfc2136.tsigSecret | b64enc | quote }}
  {{- end }}
  {{- if eq $solverDns01.provider "route53" }}
  secret-access-key: {{ $solverDns01.route53.secretAccessKey | b64enc | quote }}
  {{- end }}
...
  {{- end }}
{{- end }}
