{{- if index .Values "packages" "prometheus-stack" "grafana" "enabled" }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.organization }}.{{ .Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Release.Namespace }}
spec:
  ambassador_id:
    - {{ include "common.ingressController.id" (merge (dict "networkPlane" "management") .) }}
  prefix: /
  host: {{ include "prometheus-stack.grafana.ingress.host" (merge (dict "networkPlane" "management") .) }}
  service: {{ .Release.Name }}-grafana.{{ .Release.Namespace }}:80
  bypass_auth: true
...
{{- end }}
