{
 "title": "RabbitMQ Operator",
 "tags": [
  "ci/cd",
  "argo-cd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(controller_runtime_active_workers{container=\"rabbitmq-cluster-operator\"},namespace)"
    }
   },
   { "name": "job", "label": "Job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of goroutines that currently exist",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"$namespace\", job=~\"$job\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Number of megabytes allocated and still in use",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=~\"$namespace\", job=~\"$job\"} / 1048576",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total number of bytes allocated, even if freed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(container, service) (increase(go_memstats_alloc_bytes_total{namespace=~\"$namespace\", job=~\"$job\"}[$__rate_interval])) / 1048576",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Number of currently used workers per controller",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container, controller, job) (controller_runtime_active_workers{job=~\"$job\", namespace=~\"$namespace\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciles RabbitMQ Cluster Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Maximum number of concurrent reconciles per controller",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container, controller, job) (controller_runtime_max_concurrent_reconciles{job=~\"$job\", namespace=~\"$namespace\", service=\"rabbitmq-operator-rabbitmq-cluster-operator-metrics\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Total number of reconciliations error per controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(container, controller) (increase(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\", result=\"error\", service=\"rabbitmq-operator-rabbitmq-cluster-operator-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Total number of reconciliations requeue per controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(container, controller) (increase(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\", result=\"requeue\", service=\"rabbitmq-operator-rabbitmq-cluster-operator-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Total number of reconciliations requeue_after per controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(container, controller) (increase(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\", result=\"requeue_after\", service=\"rabbitmq-operator-rabbitmq-cluster-operator-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Total number of reconciliations success per controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(container, controller) (increase(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\", result=\"success\", service=\"rabbitmq-operator-rabbitmq-cluster-operator-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciles RabbitMQ Messaging Topology Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Current number of admission requests being served",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container, controller, job, webhook) (controller_runtime_webhook_requests_in_flight{job=~\"$job\", namespace=~\"$namespace\"})",
     "legendFormat": "{{webhook}}"
    }
   ]
  },
  {
   "title": "Maximum number of concurrent reconciles per controller",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container, controller, job) (controller_runtime_max_concurrent_reconciles{job=~\"$job\", namespace=~\"$namespace\", service=\"rabbitmq-operator-rabbitmq-messaging-topology-operator-metrics\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Total number of reconciliations error per controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum by(container, controller) (increase(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\", result=\"error\", service=\"rabbitmq-operator-rabbitmq-messaging-topology-operator-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Total number of reconciliations requeue per controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by(container, controller) (increase(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\", result=\"requeue\", service=\"rabbitmq-operator-rabbitmq-messaging-topology-operator-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Total number of reconciliations requeue_after per controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum by(container, controller) (increase(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\", result=\"requeue_after\", service=\"rabbitmq-operator-rabbitmq-messaging-topology-operator-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Total number of reconciliations success per controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum by(container, controller) (increase(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\", result=\"success\", service=\"rabbitmq-operator-rabbitmq-messaging-topology-operator-metrics\"}[$__rate_interval]))",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}