---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: {{ $.Values.organization }}.{{ $.Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ $.Release.Name }}
  namespace: default
stringData:
  {{- range $index, $ecr := index .Values "packages" "registry-credentials" "registries" "ecr" }}
  AWS_ACCESS_KEY_ID_{{ $index }}: "{{ $ecr.awsAccessKeyId }}"
  AWS_SECRET_ACCESS_KEY_{{ $index }}: "{{ $ecr.awsSecretAccessKey }}"
  {{- end }}
...
