---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-queue-has-no-consumers
  namespace: {{ .Values.environment }}-prometheus-stack
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.organization }}.{{ .Values.project }}
    app.kubernetes.io/managed-by: kubepak
    role: alert-rules
    release: prometheus-stack
spec:
  groups:
  - name: rabbitmq
    rules:
    - alert: QueueHasNoConsumers
      expr: |
          (
            ((rabbitmq_detailed_queue_consumers{vhost="/", queue=~".*"} == 0) + rabbitmq_detailed_queue_messages) > 0
          ) * on (instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info
      for: 10m
      annotations:
        description: |
          Over the last 10 minutes, non-empty queue `{{`{{ $labels.queue }}`}}` with {{`{{ $value }}`}} messages
          in virtual host `{{`{{ $labels.vhost }}`}}` didn't have any consumers in
          RabbitMQ cluster `{{`{{ $labels.rabbitmq_cluster }}`}}` in namespace `{{`{{ $labels.namespace }}`}}`.
        summary: |
          Messages are sitting idle in the queue, without any processing.
          This alert is highly application specific (and e.g. doesn't make sense for stream queues).
      labels:
        rulesgroup: rabbitmq
        severity: warning
