---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-queue-is-growing
  namespace: {{ .Values.environment }}-prometheus-stack
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.organization }}.{{ .Values.project }}
    app.kubernetes.io/managed-by: kubepak
    role: alert-rules
    release: prometheus-stack
spec:
  groups:
  - name: rabbitmq
    rules:
    - alert: QueueIsGrowing
      # `> 1` because of floating point rounding errors
      expr: |
          (
              avg_over_time(rabbitmq_detailed_queue_messages[10m]) - avg_over_time(rabbitmq_detailed_queue_messages[10m] offset 1m) > 1
          ) * on (instance, job) group_left(rabbitmq_cluster) rabbitmq_identity_info
      for: 10m
      annotations:
        description: |
          Over the last 10 minutes, queue `{{`{{ $labels.queue }}`}}` in virtual host `{{`{{ $labels.vhost }}`}}`
          was growing. 10 minute moving average has grown by {{`{{ $value }}`}}.
          This happens in RabbitMQ cluster `{{`{{ $labels.rabbitmq_cluster }}`}}` in namespace `{{`{{ $labels.namespace }}`}}`.
        summary: |
          Queue size is steadily growing over time.
      labels:
        rulesgroup: rabbitmq
        severity: warning
