{{- $isPrometheusMetricsEnabled := include "common.context.contains" (merge (dict "value" "prometheus-metrics") .) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.organization }}.{{ .Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ .Release.Name }}
  namespace: {{ index .Values "packages" "argo-cd" "namespace" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.environment }}-{{ .Values.organization }}-{{ .Values.project }}
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: {{ .Values.packages.vault.chartVersion }}
    chart: vault
    helm:
      parameters:
        - name: fullnameOverride
          value: "{{ .Release.Name }}"
        - name: global.serverTelemetry.prometheusOperator
          value: "{{ $isPrometheusMetricsEnabled }}"
        {{- if .Values.packages.vault.image.repository }}
        - name: injector.agentImage.repository
          value: "{{ .Values.packages.vault.image.repository }}"
        - name: server.image.repository
          value: "{{ .Values.packages.vault.image.repository }}"
        {{- end }}
        {{- if .Values.packages.vault.image.tag }}
        - name: injector.agentImage.tag
          value: "{{ .Values.packages.vault.image.tag }}"
        - name: server.image.tag
          value: "{{ .Values.packages.vault.image.tag }}"
        {{- end }}
        {{- if .Values.packages.vault.injector.image.repository }}
        - name: injector.image.repository
          value: "{{ .Values.packages.vault.injector.image.repository }}"
        {{- end }}
        {{- if .Values.packages.vault.injector.image.tag }}
        - name: injector.image.tag
          value: "{{ .Values.packages.vault.injector.image.tag }}"
        {{- end }}
      values: |
        {{- include "common.registryCredentials.imagePullSecrets" . | nindent 8 }}
        server:
          {{- if or .Values.packages.vault.seal .Values.packages.vault.backend.postgresql.enabled }}
          extraArgs: "-config=/vault/userconfig/extra-config/extra-config.hcl"
          {{- end }}
          {{- if .Values.packages.vault.ha.enabled }}
          ha:
            enabled: {{ .Values.packages.vault.ha.enabled }}
            replicas: {{ .Values.packages.vault.ha.replicas }}
            raft:
              enabled: {{ .Values.packages.vault.ha.raft }}
              config: |
                ui = true
                listener "tcp" {
                  tls_disable = 1
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  telemetry {
                    unauthenticated_metrics_access = "true"
                  }
                }
                storage "raft" {
                  path = "/vault/data"
                }
                service_registration "kubernetes" {}
                telemetry {
                  disable_hostname = true
                  prometheus_retention_time = "30s"
                }
            config: |
              ui = true
              listener "tcp" {
                tls_disable = "true"
                address = "[::]:8200"
                cluster_address = "[::]:8201"
                telemetry {
                  unauthenticated_metrics_access = "true"
                }
              }
              service_registration "kubernetes" {}
              telemetry {
                disable_hostname = true
                prometheus_retention_time = "30s"
              }
          {{- end }}
          serviceAccount:
            annotations:
              {{- toYaml .Values.packages.vault.serviceAccount.annotations | nindent 14 }}
          {{- if not .Values.packages.vault.ha.enabled }}
          standalone:
            config: |
              ui = true
              listener "tcp" {
                tls_disable = "true"
                address = "[::]:8200"
                cluster_address = "[::]:8201"
                telemetry {
                  unauthenticated_metrics_access = "true"
                }
              }
              storage "file" {
                path = "/vault/data"
              }
              {{- range $sealMechanism, $sealConfig := .Values.packages.vault.seal }}
              seal "{{ $sealMechanism }}" {
                {{- range $key, $value := $sealConfig }}
                {{ $key }} = "{{ $value }}"
                {{- end }}
              }
              telemetry {
                disable_hostname = true
                prometheus_retention_time = "30s"
              }
              {{- end }}
          {{- end }}
          volumes:
            {{- if .Values.packages.vault.tls.ca.srcFilePath }}
            - name: ca-certificates
              configMap:
                name: {{ .Release.Name }}-ca-certificates
            {{- end }}
            - name: "extra-config"
              secret:
                defaultMode: 420
                secretName: "{{ .Release.Name }}-extra-config"
                optional: true
          volumeMounts:
            {{- if .Values.packages.vault.tls.ca.srcFilePath }}
            - name: ca-certificates
              readOnly: true
              mountPath: {{ .Values.packages.vault.tls.ca.dstFilePath | dir }}
            {{- end }}
            - name: "extra-config"
              mountPath: "/vault/userconfig/extra-config"
              readOnly: true
        serverTelemetry:
          serviceMonitor:
            enabled: {{ $isPrometheusMetricsEnabled }}
            authorization:
              credentials:
                name: "{{ .Release.Name }}-metrics-client"
                key: token
            selectors:
              release: prometheus-stack
  destination:
    server: {{ .Values.kubernetes.server }}
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
...
