{{- if or .Values.packages.vault.seal .Values.packages.vault.backend.postgresql.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-extra-config
  namespace: {{ .Release.Namespace }}
stringData:
  extra-config.hcl: |
    {{- if .Values.packages.vault.backend.postgresql.enabled }}
    storage "postgresql" {
      connection_url="postgres://{{ .Values.packages.vault.backend.postgresql.username }}:{{ .Values.packages.vault.backend.postgresql.password }}@{{ .Values.packages.vault.backend.postgresql.host }}:{{ .Values.packages.vault.backend.postgresql.port }}/{{ .Values.packages.vault.backend.postgresql.dbname }}"
      ha_enabled={{ .Values.packages.vault.backend.postgresql.ha_enabled }}
    }
    {{- end }}
    {{- range $sealMechanism, $sealConfig := .Values.packages.vault.seal }}
    seal "{{ $sealMechanism }}" {
      {{- range $key, $value := $sealConfig }}
      {{ $key }} = "{{ $value }}"
      {{- end }}
    }
    {{- end }}
  {{- end }}