---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.organization }}.{{ .Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
data:
  credentials: {{ index .Values "packages" "crossplane-azure-provider" "dbsecret" | b64enc | quote }}
...
