packages:
  crossplane:
    image:
      repository:
      tag:
    pod:
      nodeSelector: {}
      tolerations: []
      affinity: {}
      container:
        resources: {}
    rbacManager:
      pod:
        nodeSelector: {}
        tolerations: []
        affinity: {}
        container:
          resources: {}
