---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.organization }}.{{ .Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ .Release.Name }}
  namespace: {{ index .Values "packages" "argo-cd" "namespace" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.environment }}-{{ .Values.organization }}-{{ .Values.project }}
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: {{ .Values.packages.postgresql.chartVersion }}
    chart: postgresql
    helm:
      parameters:
        - name: fullnameOverride
          value: "{{ .Release.Name }}"
        {{- if .Values.packages.postgresql.image.registry }}
        - name: image.registry
          value: "{{ .Values.packages.postgresql.image.registry }}"
        {{- end }}
        {{- if .Values.packages.postgresql.image.repository }}
        - name: image.repository
          value: "{{ .Values.packages.postgresql.image.repository }}"
        {{- end }}
        {{- if .Values.packages.postgresql.image.tag }}
        - name: image.tag
          value: "{{ .Values.packages.postgresql.image.tag }}"
        {{- end }}
        - name: auth.enablePostgresUser
          value: "true"
        - name: auth.postgresPassword
          value: "{{ .Values.packages.postgresql.auth.postgresPassword }}"
        {{- if .Values.packages.postgresql.primary.extendedConfigmap }}
        - name: primary.existingExtendedConfigmap
          value: "{{ .Values.packages.postgresql.primary.extendedConfigmap }}"
        {{- end }}
        - name: primary.initdb.user
          value: "postgres"
        - name: primary.initdb.password
          value: "{{ .Values.packages.postgresql.auth.postgresPassword }}"
        - name: primary.persistence.size
          value: "{{ .Values.packages.postgresql.persistence.size }}"
        {{- if .Values.packages.postgresql.tls.enabled }}
        - name: tls.enabled
          value: "true"
        - name: tls.certificatesSecret
          value: "{{ .Release.Name }}-tls"
        - name: tls.certFilename
          value: "tls.crt"
        - name: tls.certKeyFilename
          value: "tls.key"
          {{- if .Values.packages.postgresql.tls.ca }}
        - name: tls.certCAFilename
          value: "ca.crt"
          {{- end }}
        {{- end }}
      values: |
        global:
          {{- include "common.registryCredentials.imagePullSecrets" . | nindent 10 }}
        primary:
          nodeSelector:
            {{- toYaml .Values.packages.postgresql.primary.pod.nodeSelector | nindent 12 }}
          tolerations:
            {{- toYaml .Values.packages.postgresql.primary.pod.tolerations | nindent 12 }}
          affinity:
            {{- toYaml .Values.packages.postgresql.primary.pod.affinity | nindent 12 }}
          resources:
            {{- toYaml .Values.packages.postgresql.primary.pod.container.resources | nindent 12 }}
  destination:
    server: {{ .Values.kubernetes.server }}
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
...
