{{- if .Values.packages.postgresql.tls.enabled }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.organization }}.{{ .Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ .Release.Name }}-tls
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.packages.postgresql.tls.cert_b64 | quote }}
  tls.key: {{ .Values.packages.postgresql.tls.key_b64 | quote }}
  {{- if .Values.packages.postgresql.tls.ca }}
  ca.crt: {{ .Values.packages.postgresql.tls.ca_b64 | quote }}
  {{- end }}
...
{{- end }}
