{{- if eq (include "common.context.contains" (merge (dict "value" "prometheus-metrics") .)) "true" }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.organization }}.{{ .Values.project }}
    app.kubernetes.io/managed-by: kubepak
  name: {{ .Release.Name }}-servicemonitor
  namespace: {{ .Release.Namespace }}
data:
  user: {{ index .Values "packages" "nexus" "auth" "metrics-reader" "username" | b64enc }}
  password: {{ index .Values "packages" "nexus" "auth" "metrics-reader" "password" | b64enc }}
...
{{- end }}
